Fix pip install for run-local-test
This currently fails with:
ERROR: Double requirement given:
mock (from -r molecule-requirements.txt (line 10))
(already in mock>=2.0.0 (from -r test-requirements.txt (line 3)), name='mock')

The tox linters job uses the same pip requirements files but doesn't hit this
because it also passes the openstack upper constraints files, so do the same in
run-local-test.

Change-Id: I12602801147b99a4c17a02cfd43239897ee049f3