Fix role-addition CI
By artificially setting the upper constraint file we ignore
global-requirements which then creates errors like the following:

role-addition run-test: commands[2] | pip check
setting PATH=/home/zuul/src/opendev.org/openstack/tripleo-ansible/.tox/role-addition/bin:/home/zuul/.local/bin:/home/zuul/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
[43268] /home/zuul/src/opendev.org/openstack/tripleo-ansible$ /home/zuul/src/opendev.org/openstack/tripleo-ansible/.tox/role-addition/bin/pip check
openstacksdk 0.48.0 has requirement decorator>=4.4.1, but you have decorator 4.2.1.
ERROR: InvocationError for command /home/zuul/src/opendev.org/openstack/tripleo-ansible/.tox/role-addition/bin/pip check (exited with code 1)

A job test that was failing previously with the above error, now passed
correctly:
- Before: https://zuul.opendev.org/t/openstack/build/8ad3a5951133418e8be132db218a4480
- After: https://zuul.opendev.org/t/openstack/build/01d33b85362d430cb30b619803814677

Closes-Bug: #1893734

Change-Id: I0e5f4692efe387d97f940b5323e593a94b6f833a
(cherry picked from commit 8e2a54d5d5a8170591647473f3e79573928ff3ef)