Fix molecule jobs after release of cryptography3.4
Molecule jobs[0] fails with below error:-

ModuleNotFoundError: No module named 'setuptools_rust'

This error appeared following the release of cryptography 3.4, which
now includes Rust code. It can be installed without Rust using a
Python wheel, but only with more recent pip than version 9.0.3
available as RPM on CentOS 8.

The cryptography bug report [1] recommends pip>=19.1.1.

[0] https://e99635be2c7386b5beda-3dea60a35fb0d38e41c535f13b48e895.ssl.cf1.rackcdn.com/773531/1/gate/tripleo-ansible-centos-8-molecule-tripleo_network_config/b1284cd/job-output.txt
[1] https://github.com/pyca/cryptography/issues/5753
Related-Bug: #1915101

Change-Id: I3650a68640a0ec846be24014ebc6a71110b2f6f7
(cherry picked from commit f8a286cf3014c05105075d033178172ac030dcb6)